flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/TomSmeets/xmonad-contrib/
    commit: 305c8eff0d56552e541bb37eb19e48212454834d
flags:
  xmonad-contrib:
    use_xft: true
extra-deps:
- X11-xft-0.3.1
resolver: lts-6.10
